import React, { useState, useRef, useEffect } from "react";

const C = {
  navy:"#0F2744",blue:"#1E4D8C",sky:"#2E86DE",
  green:"#1A9E5F",red:"#D63031",orange:"#E67E22",
  light:"#F4F7FB",white:"#FFFFFF",grey:"#6B7280",border:"#E2E8F0",
};

const T = {
  en:{
    login:"Login",createAccount:"Create account",signIn:"Sign in →",createMyAccount:"Create my account →",
    restrictedAccess:"Restricted access · Confidential",fillAllFields:"Fill in all fields.",
    authFailed:"Authentication failed.",networkError:"Network error.",
    language:"Language",searchLanguage:"Search language",
    langSubtitle:"Type to search any language in the world",
    langPlaceholder:"Type to search… Français, Arabic, Spanish…",
    selected:"✓ Selected",next:"Next →",back:"← Back",launch:"🚀 Launch NarcoSync",saving:"Saving…",
    location:"Location",locationSubtitle:"Where is your pharmacy located?",
    country:"Country",province:"Province",state:"State",regionCity:"Region / City",
    selectProvince:"Select province…",selectState:"Select state…",enterRegion:"Enter your region or city",
    yourPharmacy:"Your Pharmacy",pharmacySubtitle:"Complete your pharmacy profile",
    pharmacyInfoSection:"📋 Pharmacy Info",teamSection:"👤 Team",planSection:"💳 Subscription Plan",
    pharmacyName:"Pharmacy chain / banner",permitNumber:"Permit / License number",
    pharmacyAddress:"Pharmacy address",pharmacyPhone:"Pharmacy phone",pharmacyEmail:"Pharmacy email",
    pharmacySystem:"Dispensing software system",
    pharmacySystemHint:"Your pharmacy management system — used to parse reconciliation files",
    pharmacySystemPlaceholder:"Search your software…",
    pharmacistOwner:"Pharmacist-owner name",pharmacistEmail:"Pharmacist-owner email",
    managerName:"Your name (team lead / manager)",
    pharmacyPlaceholder:"Search chain or type custom name…",
    pharmacyNameHint:"e.g. Pharmaprix, Jean Coutu, Independent…",
    permitPlaceholder:"e.g. OPQ-12345",addressPlaceholder:"Start typing your address…",
    addressHint:"Type street number + name to search",
    phonePlaceholder:"514-000-0000",emailPlaceholder:"info@pharmacy.com",
    ownerPlaceholder:"Full name",ownerEmailPlaceholder:"owner@pharmacy.com",managerPlaceholder:"Your full name",
    stripeNote:"💳 Payment setup via Stripe after onboarding — no card required now.",
    requiredNote:"* Required fields",planRequired:"⚠️ Please select a plan to continue.",
    welcomeToNarco:"Welcome to NarcoSync",stepOf:"Step",ofTotal:"of",
    dashboard:"Dashboard",reconciliation:"Reconciliation",history:"History",
    clinical:"Clinical",plans:"Plans",signOut:"🔒 Sign out",loggedInAs:"LOGGED IN AS",
    welcomeMsg:"Welcome to NarcoSync 👋",liveMsg:"🎉 NarcoSync is live!",
    liveSubMsg:"Connected to Supabase · Ready for your first reconciliation",
    emptyState:"No cycles yet",emptyStateSub:"Complete your first reconciliation to see stats here.",
    newReco:"⚡ + New Reconciliation",newRecoTitle:"⚡ New Reconciliation",
    newRecoSub:"Upload your inventory and sales files · Any format",
    inventoryLabel:"📦
